"""
                                                                        Even Fibonacci numbers
                                                                                Problem 2 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
                                1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

#STORING FIBONACCI NUMBERS IN A LIST


t1=1
t2=2
t3=0
fib=[1,2]
"""
for i in range(0,10-2,1):
        t3=t1+t2
        fib.append(t3) 
        t1=t2
        t2=t3
print fib

"""

while True:
        t3=t1+t2
        if(t3<=4000000):
                fib.append(t3)
        else:
                break
        t1=t2
        t2=t3
print fib        

#ITERATING OVER THE LIST

ctr=0
for i in fib:
        if i%2==0 :
                ctr+=i

print ctr
